stages:
    - test
    - build

.node-base:
    image: node:22
    stage: test
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - .npm/
    before_script:
        - npm ci --cache .npm --prefer-offline

test:
    extends: .node-base
    script:
        - npm run test:unit
        - echo $USERNAME

build:
    extends: .node-base
    script:
        - ls