version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: articles_db
      DB_USER: articles_user
      DB_PASSWORD: articles_password
    volumes:
      - ./backend:/app
    networks:
      - app-network
    command: >
      bash -c "python -m venv venv &&
             source venv/bin/activate &&
             pip install -r requirements/requirements.txt &&
             python manage.py migrate &&
             python manage.py loaddata --format json ./fixtures/dev-fixtures.json &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_API: http://localhost:8000  
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    command: >
      sh -c "npm install && npm run dev -- --host"

  db:
    image: postgres:17.2
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: articles_db
      POSTGRES_USER: articles_user
      POSTGRES_PASSWORD: articles_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
