name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.2
        env:
          POSTGRES_DB: articles_db
          POSTGRES_USER: articles_user
          POSTGRES_PASSWORD: articles_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U articles_user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      # 1. Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Tests unitaires du backend
      - name: Setup Python and run backend tests
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Run backend tests
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements/dev.txt
          python manage.py test

      # 3. Tests unitaires du frontend
      - name: Setup Node.js and run frontend tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run frontend tests
        run: |
          cd frontend
          npm install
          npm run test:unit

      # 4. Build des images Docker
      - name: Build backend Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/projetcicd-backend:latest -f backend/Dockerfile backend
      - name: Build frontend Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/projetcicd-frontend:latest -f frontend/Dockerfile frontend

      # 5. Connexion à GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # 6. Pousser les images sur GHCR
      - name: Push backend image to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/projetcicd-backend:latest

      - name: Push frontend image to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/projetcicd-frontend:latest
